# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

FROM sawtooth-seth-cli AS debs

WORKDIR /project

COPY ./cli/packaging /project/packaging

RUN pkg_dir=/project/build/debs/ \
 && CHANGELOG_DIR="debian/usr/share/doc/sawtooth-seth" \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && mkdir -p $pkg_dir \
 && mkdir -p debian/DEBIAN \
 && mkdir -p $CHANGELOG_DIR \
 && cp packaging/ubuntu/* debian \
 && cp debian/changelog $CHANGELOG_DIR \
 && mv debian/changelog $CHANGELOG_DIR/changelog.Debian \
 && gzip --best $CHANGELOG_DIR/changelog \
 && gzip --best $CHANGELOG_DIR/changelog.Debian \
 && mv debian/control debian/DEBIAN \
 && PACKAGENAME=$(awk '/^Package:/ { print $2 }' debian/DEBIAN/control) \
 && PACKAGEVERSION=$(dpkg-parsechangelog -S version -l $CHANGELOG_DIR/changelog.gz) \
 && PACKAGEARCH=$(dpkg-architecture -qDEB_BUILD_ARCH) \
 && mkdir debian/usr/bin \
 && cp -R $(which seth) debian/usr/bin \
 && fakeroot dpkg-deb --build debian \
 && mv debian.deb $pkg_dir/"${PACKAGENAME}_${PACKAGEVERSION}_${PACKAGEARCH}.deb"

FROM ubuntu:xenial

RUN mkdir /install

VOLUME /install

COPY --from=debs /project/build/debs/sawtooth-seth-cli_*amd64.deb /install

RUN apt-get update \
 && apt-get install -y -q dpkg-dev \
 && cd /install \
 && dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz \
 && echo "deb file:/debs ./" >> /etc/apt/sources.list \
 && apt-get update \
 && apt-get install sawtooth-seth-cli -y -q --allow-unauthenticated \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
